# This file defines the principal settings for this project

# Definition of the grfs
REPO_NAME           ?= polroad

# This is the filename part common to the grf file, main source file and the tar name
BASE_FILENAME       ?= polroad

# Documentation files
DOC_FILES ?= docs/license.txt docs/changelog.txt

# Possible offset to NewGRF version. Increase by one, if a release
# branch is added to the repository
REPO_BRANCH_VERSION ?= 0

# Directory structure
SCRIPT_DIR          ?= scripts

# Uncomment in order to make use of gimp scripting. See the file
# for a description of the format
# GFX_SCRIPT_LIST_FILES      := gfx/png_source_list

# If needed, declare the minimum NML requirements
# REQUIRED_NML_BRANCH  = 0.3
# MIN_NML_REVISION     = 0
